### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by grantcarthew** [yamalight/rethinkdb-pubsub#3]
Hi Tim,

I tried to use `rethinkdb-pubsub` with no luck so I forked and ran the tests.
They fail. I spent a some time fault finding, however I am going to switch to the original code from the RethinkDB team.

I would like to use this package.   It would be a shame to see your effort go to waste.

Thanks.

**Comment by grantcarthew** [comment]
Here is the error message displayed when running the tests;

``` sh
# Exchange
# # should send message to subscriber
Unhandled rejection ReqlOpFailedError: Table `test.testexchange` is ambiguous; there are multiple tables with that name in:
r.table("testexchange").changes()("new_val").filter(function(var_0) { return var_0("topic").eq("test.out"); })
^^^^^^^^^^^^^^^^^^^^^^^                                                                                
    at ReqlOpFailedError.ReqlError [as constructor] (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:23:13)
    at ReqlOpFailedError.ReqlRuntimeError [as constructor] (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:90:51)
    at ReqlOpFailedError.ReqlAvailabilityError [as constructor] (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:167:56)
    at new ReqlOpFailedError (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:178:52)
    at mkErr (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/util.js:177:10)
    at TcpConnection.Connection._processResponse (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/net.js:152:16)
    at TcpConnection.Connection._data (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/net.js:122:12)
    at Socket.<anonymous> (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/net.js:683:32)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
Unhandled rejection ReqlOpFailedError: Table `test.testexchange` is ambiguous; there are multiple tables with that name in:
r.table("testexchange").filter({"topic": "test.out"}).update({"payload": "test", "updated_on": r.now()})
^^^^^^^^^^^^^^^^^^^^^^^                                                                                
    at ReqlOpFailedError.ReqlError [as constructor] (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:23:13)
    at ReqlOpFailedError.ReqlRuntimeError [as constructor] (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:90:51)
    at ReqlOpFailedError.ReqlAvailabilityError [as constructor] (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:167:56)
    at new ReqlOpFailedError (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/errors.js:178:52)
    at mkErr (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/util.js:177:10)
    at TcpConnection.Connection._processResponse (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/net.js:152:16)
    at TcpConnection.Connection._data (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/net.js:122:12)
    at Socket.<anonymous> (/home/grant/rethinkdb-pubsub/node_modules/rethinkdb/net.js:683:32)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)

```

**Comment by yamalight** [comment]
Since it's literally the same code as in official docs, you'll most likely get the same errors.

I'm looking into it. Looks like something was change w.r.t. request queuing, that's why it throws now.

**Comment by yamalight** [comment]
fixed, pushed and published.

**Comment by grantcarthew** [comment]
Oh,  good work. I can't test it yet but will do when can.  Thanks mate.
